name: Deploy to Render

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Render CLI
        run: npm install -g @render/cli

      - name: Log in to Render
        env:
          RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        run: render login --email $RENDER_EMAIL --token $RENDER_TOKEN

      - name: Deploy to Render
        run: render deploy

