name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETKEYAWS }}
          aws-region: us-east-1

      - name: Install Elastic Beanstalk CLI
        run: |
          # Install Elastic Beanstalk CLI
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install awsebcli

      - name: Configure Elastic Beanstalk CLI
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.ACCESSKEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SECRETKEYAWS }}" >> $GITHUB_ENV
          eb configure set aws_access_key_id ${{ secrets.ACCESSKEY }}
          eb configure set aws_secret_access_key ${{ secrets.SECRETKEYAWS }}
          eb configure set default.region us-east-1
        env:
          AWS_DEFAULT_REGION: us-east-1



      # Initialize Elastic Beanstalk Environment (add this step)
      - name: Initialize Elastic Beanstalk Environment
        run: |
          # Initialize Elastic Beanstalk environment
          eb init -r us-east-1 -p "Node.js 18" TestingMVBack-env
          eb use TestingMVBack-env

      - name: Deploy to Elastic Beanstalk
        run: |
          # Deploy to Elastic Beanstalk
          eb deploy TestingMVBack-env
