name: AWS Elastic Beanstalk Deployment

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETKEYAWS }}
          aws-region: us-east-1

      - name: Install Elastic Beanstalk CLI
        run: |
          # Install Elastic Beanstalk CLI
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install awsebcli

      - name: Initialize Elastic Beanstalk Environment
        run: |
          # Initialize Elastic Beanstalk environment
          eb init -r us-east-1 -p "Node.js 16" Testing1-env
          eb use Testing1-env

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy Testing1-env
